import streamlit as st
import pandas as pd
import plotly.express as px
from datetime import date, datetime

st.set_page_config(page_title="Plano de Voo: Auditor TI SEFAZ/SE", layout="wide")

# ======= HEADER =======
st.title("🚀 Plano de Voo: SEFAZ/SE")
st.markdown("Foco, força e fé na sua aprovação!")

# ======= PAINEL =======
st.header("📊 Painel de Controle")

col1, col2, col3 = st.columns(3)

# Contagem regressiva
exam_date = date(2025, 9, 28)
days_left = (exam_date - date.today()).days
with col1:
    st.subheader("Contagem Regressiva")
    st.metric("Dias até a prova", f"{days_left} dias")

# Progresso geral
if "progress" not in st.session_state:
    st.session_state.progress = 0
with col2:
    st.subheader("Progresso Geral")
    st.progress(st.session_state.progress / 100)
    st.write(f"{st.session_state.progress}% concluído")

# Foco do dia
with col3:
    st.subheader("Foco do Dia")
    st.info("📌 Direito Tributário")

# ======= ANÁLISE =======
st.header("📈 Análise Estratégica do Edital")

exam_data = {
    "Prova": ["Conhecimentos Específicos II (TI - P3)", "Prova Discursiva (TI - P4)", "Conhecimentos Específicos I (P2)", "Conhecimentos Gerais (P1)"],
    "Peso": [90, 80, 100, 10]
}
df_exam = pd.DataFrame(exam_data)
fig = px.pie(df_exam, names="Prova", values="Peso", title="Distribuição de Pontos no Concurso")
st.plotly_chart(fig, use_container_width=True)

# ======= CRONOGRAMA =======
st.header("📅 Cronograma de Estudos")

schedule = {
    "Segunda": ["Português", "Raciocínio Lógico", "Exercícios"],
    "Terça": ["Constitucional", "Contabilidade", "Admin"],
    "Quarta": ["Custos", "Exercícios", "Empresarial"],
    "Quinta": ["AFO", "Exercícios", "Sergipe"],
    "Sexta": ["Revisão", "Exercícios", "Tributário"],
}
df_schedule = pd.DataFrame(schedule, index=["Manhã", "Tarde", "Noite"])
st.dataframe(df_schedule)

# ======= EDITAL =======
st.header("📖 Edital Verticalizado")

import pandas as pd

if "syllabus" not in st.session_state:
    st.session_state.syllabus = pd.DataFrame([{"Código": "1", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O papel do Estado e a atuação do governo nas finanças públicas", "Assunto": "-", "Concluído": False},
    {"Código": "1.1", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O papel do Estado", "Assunto": "Formas e dimensões da intervenção da administração na economia", "Concluído": False},
    {"Código": "1.2", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O papel do Estado", "Assunto": "Funções do orçamento público", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Orçamento público", "Assunto": "-", "Concluído": False},
    {"Código": "2.1", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Orçamento público", "Assunto": "Conceito", "Concluído": False},
    {"Código": "2.2", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Orçamento público", "Assunto": "Técnicas orçamentárias", "Concluído": False},
    {"Código": "2.3", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Orçamento público", "Assunto": "Princípios orçamentários", "Concluído": False},
    {"Código": "2.4", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Orçamento público", "Assunto": "Ciclo orçamentário", "Concluído": False},
    {"Código": "2.5", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Orçamento público", "Assunto": "Processo orçamentário", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "-", "Concluído": False},
    {"Código": "3.1", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "Sistema de planejamento e de orçamento federal", "Concluído": False},
    {"Código": "3.2", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "Plano plurianual", "Concluído": False},
    {"Código": "3.3", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "Diretrizes orçamentárias", "Concluído": False},
    {"Código": "3.4", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "Orçamento anual", "Concluído": False},
    {"Código": "3.5", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "Outros planos e programas", "Concluído": False},
    {"Código": "3.6", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "Sistema e processo de orçamentação", "Concluído": False},
    {"Código": "3.7", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "Classificações orçamentárias", "Concluído": False},
    {"Código": "3.8", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "Estrutura programática", "Concluído": False},
    {"Código": "3.9", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "O orçamento público no Brasil", "Assunto": "Créditos ordinários e adicionais", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Programação e execução orçamentária e financeira", "Assunto": "-", "Concluído": False},
    {"Código": "4.1", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Programação e execução orçamentária", "Assunto": "Descentralização orçamentária e financeira", "Concluído": False},
    {"Código": "4.2", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Programação e execução orçamentária", "Assunto": "Acompanhamento da execução", "Concluído": False},
    {"Código": "4.3", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Programação e execução orçamentária", "Assunto": "Sistemas de informações", "Concluído": False},
    {"Código": "4.4", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Programação e execução orçamentária", "Assunto": "Alterações orçamentárias", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Receita pública", "Assunto": "-", "Concluído": False},
    {"Código": "5.1", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Receita pública", "Assunto": "Conceito e classificações", "Concluído": False},
    {"Código": "5.2", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Receita pública", "Assunto": "Estágios", "Concluído": False},
    {"Código": "5.3", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Receita pública", "Assunto": "Fontes", "Concluído": False},
    {"Código": "5.4", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Receita pública", "Assunto": "Dívida ativa", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Despesa pública", "Assunto": "-", "Concluído": False},
    {"Código": "6.1", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Despesa pública", "Assunto": "Conceito e classificações", "Concluído": False},
    {"Código": "6.2", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Despesa pública", "Assunto": "Estágios", "Concluído": False},
    {"Código": "6.3", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Despesa pública", "Assunto": "Restos a pagar", "Concluído": False},
    {"Código": "6.4", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Despesa pública", "Assunto": "Despesas de exercícios anteriores", "Concluído": False},
    {"Código": "6.5", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Despesa pública", "Assunto": "Dívida flutuante e fundada", "Concluído": False},
    {"Código": "6.6", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Despesa pública", "Assunto": "Suprimento de fundos", "Concluído": False},
    {"Código": "7", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Lei de Responsabilidade Fiscal", "Assunto": "-", "Concluído": False},
    {"Código": "7.1", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Lei de Responsabilidade Fiscal", "Assunto": "Conceitos e objetivos", "Concluído": False},
    {"Código": "7.2", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Lei de Responsabilidade Fiscal", "Assunto": "Planejamento", "Concluído": False},
    {"Código": "7.3", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Lei de Responsabilidade Fiscal", "Assunto": "Receita Pública", "Concluído": False},
    {"Código": "7.4", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Lei de Responsabilidade Fiscal", "Assunto": "Despesa Pública", "Concluído": False},
    {"Código": "7.5", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Lei de Responsabilidade Fiscal", "Assunto": "Dívida e endividamento", "Concluído": False},
    {"Código": "7.6", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Lei de Responsabilidade Fiscal", "Assunto": "Transparência, controle e fiscalização", "Concluído": False},
    {"Código": "8", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Termo de execução descentralizada, convênios, termo de referência e relatório de cumprimento de objeto", "Assunto": "-", "Concluído": False},
    {"Código": "9", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Tesouro Gerencial", "Assunto": "-", "Concluído": False},
    {"Código": "10", "Grupo": "Geral Especifico", "Área": "ADMINISTRAÇÃO FINANCEIRA E ORÇAMENTÁRIA", "Subárea": "Decretos de Programação Orçamentária e Financeira (DPOF)", "Assunto": "-", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Sistema Tributário Nacional", "Assunto": "Princípios Gerais. Limitações do Poder de Tributar", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Direito tributário", "Assunto": "Conceito e princípios", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Tributos", "Assunto": "Conceito e espécies: Impostos, Taxas, Contribuição de Melhoria, Imunidades", "Concluído": False},
    {"Código": "3.1", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Tributos", "Assunto": "Impostos da União", "Concluído": False},
    {"Código": "3.2", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Tributos", "Assunto": "Impostos dos estados e do Distrito Federal", "Concluído": False},
    {"Código": "3.3", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Tributos", "Assunto": "Impostos dos municípios", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Repartição das receitas tributárias", "Assunto": "-", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Código Tributário Nacional", "Assunto": "Competência tributária e suas limitações. Normas gerais de direito tributário. Norma tributária: espécies; vigência e aplicação; interpretação e integração; natureza", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Obrigação tributária", "Assunto": "Conceito; espécies; fato gerador (hipótese de incidência); sujeitos ativo e passivo; solidariedade; capacidade tributária; domicílio tributário", "Concluído": False},
    {"Código": "7", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Responsabilidade tributária", "Assunto": "Responsabilidade dos Sucessores. Solidariedade e sucessão. Responsabilidade pessoal e de terceiros. Responsabilidade por infrações. Responsabilidade supletiva", "Concluído": False},
    {"Código": "8", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Crédito tributário", "Assunto": "Conceito; natureza; lançamento e suas modalidades; revisão, suspensão, extinção e exclusão; prescrição e decadência; repetição do indébito", "Concluído": False},
    {"Código": "9", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Garantias e privilégios", "Assunto": "Crédito tributário", "Concluído": False},
    {"Código": "10", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Administração Tributária", "Assunto": "Fiscalização. Sigilo Fiscal. Dívida Ativa. Certidões Negativas", "Concluído": False},
    {"Código": "11", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Lei Complementar nº 118, de 2005", "Assunto": "-", "Concluído": False},
    {"Código": "12", "Grupo": "Geral Especifico", "Área": "DIREITO TRIBUTÁRIO", "Subárea": "Reforma Tributária", "Assunto": "EC nº 132/2023 e LC nº 214/2025", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Conceitos, objetivos e finalidades da contabilidade", "Assunto": "-", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Patrimônio: componentes, equação fundamental do patrimônio, situação líquida, representação gráfica", "Assunto": "-", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Atos e fatos administrativos: conceitos, fatos permutativos, modificativos e mistos", "Assunto": "-", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Contas: conceitos, contas de débitos, contas de créditos e saldos", "Assunto": "-", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Plano de contas: conceitos, elenco de contas, função e funcionamento das contas", "Assunto": "-", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Escrituração: conceitos, lançamentos contábeis, elementos essenciais, fórmulas de lançamentos, livros de escrituração, métodos e processos, regime de competência e regime de caixa", "Assunto": "-", "Concluído": False},
    {"Código": "7", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Contabilização de operações contábeis diversas: juros, descontos, tributos, aluguéis, variação monetária/cambial, folha de pagamento, compras, vendas e provisões, depreciações e baixa de bens", "Assunto": "-", "Concluído": False},
    {"Código": "8", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Balancete de verificação: conceitos, modelos e técnicas de elaboração", "Assunto": "-", "Concluído": False},
    {"Código": "9", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Balanço patrimonial: conceitos, objetivo, composição", "Assunto": "-", "Concluído": False},
    {"Código": "10", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Demonstração de resultado de exercício: conceito, objetivo, composição", "Assunto": "-", "Concluído": False},
    {"Código": "11", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE GERAL", "Subárea": "Normas Brasileiras de Contabilidade", "Assunto": "-", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE DE CUSTOS", "Subárea": "Conceitos gerais", "Assunto": "Terminologia aplicável à contabilidade de custos", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE DE CUSTOS", "Subárea": "Conceitos e classificação", "Assunto": "Dos custos", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE DE CUSTOS", "Subárea": "Apropriação dos custos", "Assunto": "À produção", "Concluído": False},
    {"Código": "3.1", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE DE CUSTOS", "Subárea": "Apropriação dos custos", "Assunto": "Conceito e critérios de atribuição dos custos", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE DE CUSTOS", "Subárea": "Departamentalização", "Assunto": "-", "Concluído": False},
    {"Código": "4.1", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE DE CUSTOS", "Subárea": "Departamentalização", "Assunto": "Conceito, tratamento contábil, forma de apropriação e impacto no custo do produto", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE DE CUSTOS", "Subárea": "Tipos de custeio", "Assunto": "Conceitos, diferenciações, apropriação dos custos, impactos nos resultados", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE DE CUSTOS", "Subárea": "Tópicos Especiais", "Assunto": "Contabilidade Aplicada ao Setor Público", "Concluído": False},
    {"Código": "6.1", "Grupo": "Geral Especifico", "Área": "CONTABILIDADE DE CUSTOS", "Subárea": "Tópicos Especiais", "Assunto": "Custos no setor público: NBC TSP 34", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Estado, governo e administração pública", "Assunto": "-", "Concluído": False},
    {"Código": "1.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Estado, governo e administração pública", "Assunto": "Conceitos", "Concluído": False},
    {"Código": "1.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Estado, governo e administração pública", "Assunto": "Elementos", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Direito administrativo", "Assunto": "-", "Concluído": False},
    {"Código": "2.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Direito administrativo", "Assunto": "Conceito", "Concluído": False},
    {"Código": "2.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Direito administrativo", "Assunto": "Objeto", "Concluído": False},
    {"Código": "2.3", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Direito administrativo", "Assunto": "Fontes", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Ato administrativo", "Assunto": "-", "Concluído": False},
    {"Código": "3.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Ato administrativo", "Assunto": "Conceito, requisitos, atributos, classificação e espécies", "Concluído": False},
    {"Código": "3.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Ato administrativo", "Assunto": "Extinção do ato administrativo", "Concluído": False},
    {"Código": "3.2.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Extinção do ato administrativo", "Assunto": "Cassação, anulação, revogação e convalidação", "Concluído": False},
    {"Código": "3.3", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Ato administrativo", "Assunto": "Decadência administrativa", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Agentes públicos", "Assunto": "-", "Concluído": False},
    {"Código": "4.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Agentes públicos", "Assunto": "Disposições constitucionais aplicáveis", "Concluído": False},
    {"Código": "4.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "-", "Concluído": False},
    {"Código": "4.2.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Conceito", "Concluído": False},
    {"Código": "4.2.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Espécies", "Concluído": False},
    {"Código": "4.2.3", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Cargo, emprego e função pública", "Concluído": False},
    {"Código": "4.2.4", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Provimento", "Concluído": False},
    {"Código": "4.2.5", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Vacância", "Concluído": False},
    {"Código": "4.2.6", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Efetividade, estabilidade e vitaliciedade", "Concluído": False},
    {"Código": "4.2.7", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Remuneração", "Concluído": False},
    {"Código": "4.2.8", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Direitos e deveres", "Concluído": False},
    {"Código": "4.2.9", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Responsabilidade", "Concluído": False},
    {"Código": "4.2.10", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Disposições doutrinárias", "Assunto": "Processo administrativo disciplinar", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Poderes da administração pública", "Assunto": "-", "Concluído": False},
    {"Código": "5.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Poderes da administração pública", "Assunto": "Hierárquico, disciplinar, regulamentar e de polícia", "Concluído": False},
    {"Código": "5.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Poderes da administração pública", "Assunto": "Uso e abuso do poder", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Regime jurídico-administrativo", "Assunto": "-", "Concluído": False},
    {"Código": "6.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Regime jurídico-administrativo", "Assunto": "Conceito", "Concluído": False},
    {"Código": "6.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Regime jurídico-administrativo", "Assunto": "Princípios expressos e implícitos da administração pública", "Concluído": False},
    {"Código": "7", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Responsabilidade civil do Estado", "Assunto": "-", "Concluído": False},
    {"Código": "7.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Responsabilidade civil do Estado", "Assunto": "Evolução histórica", "Concluído": False},
    {"Código": "7.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Responsabilidade civil do Estado", "Assunto": "Responsabilidade civil do Estado no direito brasileiro", "Concluído": False},
    {"Código": "7.2.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Responsabilidade civil do Estado", "Assunto": "Responsabilidade por ato comissivo do Estado", "Concluído": False},
    {"Código": "7.2.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Responsabilidade civil do Estado", "Assunto": "Responsabilidade por omissão do Estado", "Concluído": False},
    {"Código": "7.3", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Responsabilidade civil do Estado", "Assunto": "Requisitos para a demonstração da responsabilidade do Estado", "Concluído": False},
    {"Código": "7.4", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Responsabilidade civil do Estado", "Assunto": "Causas excludentes e atenuantes da responsabilidade do Estado", "Concluído": False},
    {"Código": "7.5", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Responsabilidade civil do Estado", "Assunto": "Reparação do dano", "Concluído": False},
    {"Código": "7.6", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Responsabilidade civil do Estado", "Assunto": "Direito de regresso", "Concluído": False},
    {"Código": "8", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Serviços públicos", "Assunto": "-", "Concluído": False},
    {"Código": "8.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Serviços públicos", "Assunto": "Conceito", "Concluído": False},
    {"Código": "8.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Serviços públicos", "Assunto": "Elementos constitutivos", "Concluído": False},
    {"Código": "8.3", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Serviços públicos", "Assunto": "Formas de prestação e meios de execução", "Concluído": False},
    {"Código": "8.4", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Serviços públicos", "Assunto": "Delegação", "Concluído": False},
    {"Código": "8.4.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Delegação", "Assunto": "Concessão, permissão e autorização", "Concluído": False},
    {"Código": "8.5", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Serviços públicos", "Assunto": "Classificação", "Concluído": False},
    {"Código": "8.6", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Serviços públicos", "Assunto": "Princípios", "Concluído": False},
    {"Código": "9", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Organização administrativa", "Assunto": "-", "Concluído": False},
    {"Código": "9.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Organização administrativa", "Assunto": "Centralização, descentralização, concentração e desconcentração", "Concluído": False},
    {"Código": "9.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Organização administrativa", "Assunto": "Administração direta e indireta", "Concluído": False},
    {"Código": "9.3", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Organização administrativa", "Assunto": "Autarquias, fundações, empresas públicas e sociedades de economia mista", "Concluído": False},
    {"Código": "9.4", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Organização administrativa", "Assunto": "Entidades paraestatais e terceiro setor", "Concluído": False},
    {"Código": "9.4.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Organização administrativa", "Assunto": "Serviços sociais autônomos, entidades de apoio, organizações sociais, organizações da sociedade civil de interesse público", "Concluído": False},
    {"Código": "10", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Controle da administração pública", "Assunto": "-", "Concluído": False},
    {"Código": "10.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Controle da administração pública", "Assunto": "Controle exercido pela administração pública", "Concluído": False},
    {"Código": "10.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Controle da administração pública", "Assunto": "Controle judicial", "Concluído": False},
    {"Código": "10.3", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Controle da administração pública", "Assunto": "Controle legislativo", "Concluído": False},
    {"Código": "10.4", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Controle da administração pública", "Assunto": "Improbidade administrativa", "Concluído": False},
    {"Código": "10.4.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Controle da administração pública", "Assunto": "Lei nº 8.429/1992 e suas alterações", "Concluído": False},
    {"Código": "11", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Processo administrativo", "Assunto": "-", "Concluído": False},
    {"Código": "11.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Processo administrativo", "Assunto": "Lei Complementar Estadual nº 33/96 e suas alterações", "Concluído": False},
    {"Código": "12", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "-", "Concluído": False},
    {"Código": "12.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "Legislação pertinente", "Concluído": False},
    {"Código": "12.1.1", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Legislação pertinente", "Assunto": "Lei nº 14.133/2021", "Concluído": False},
    {"Código": "12.1.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Legislação pertinente", "Assunto": "Decreto nº 11.462/2013 e suas alterações (sistema de registro de preços)", "Concluído": False},
    {"Código": "12.2", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "Fundamentos constitucionais", "Concluído": False},
    {"Código": "12.3", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "Elaboração e fiscalização de contratos", "Concluído": False},
    {"Código": "12.4", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "Elaboração de projetos básicos para contratação de bens e serviços", "Concluído": False},
    {"Código": "12.5", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "Critérios de remuneração por esforço versus produto", "Concluído": False},
    {"Código": "12.6", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "Cláusulas e indicadores de nível de serviço", "Concluído": False},
    {"Código": "12.7", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "Papel do fiscalizador do contrato", "Concluído": False},
    {"Código": "12.8", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "Acompanhamento da execução contratual", "Concluído": False},
    {"Código": "12.9", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Licitações e contratos administrativos", "Assunto": "Definição e aplicação de penalidades e sanções administrativas", "Concluído": False},
    {"Código": "13", "Grupo": "Geral Especifico", "Área": "DIREITO ADMINISTRATIVO", "Subárea": "Lei Estadual nº 9.640/2025", "Assunto": "Código de Conduta e Integridade da Secretaria de Estado da Fazenda de Sergipe", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Constituição da República", "Assunto": "Constituição da República Federativa do Brasil de 1988", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Aplicabilidade das normas", "Assunto": "-", "Concluído": False},
    {"Código": "2.1", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Aplicabilidade das normas", "Assunto": "Normas de eficácia plena, contida e limitada", "Concluído": False},
    {"Código": "2.2", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Aplicabilidade das normas", "Assunto": "Normas programáticas", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Direitos e garantias fundamentais", "Assunto": "-", "Concluído": False},
    {"Código": "3.1", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Direitos e garantias fundamentais", "Assunto": "Direitos e deveres individuais e coletivos, direitos sociais, direitos de nacionalidade, direitos políticos, partidos políticos", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Organização político-administrativa", "Assunto": "-", "Concluído": False},
    {"Código": "4.1", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Organização político-administrativa", "Assunto": "Estado federal brasileiro, União, estados, Distrito Federal, municípios e territórios", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Administração pública", "Assunto": "Disposições gerais, servidores públicos", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Poder Executivo", "Assunto": "-", "Concluído": False},
    {"Código": "6.1", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Poder Executivo", "Assunto": "Atribuições e responsabilidades do presidente da República", "Concluído": False},
    {"Código": "7", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Poder Legislativo", "Assunto": "-", "Concluído": False},
    {"Código": "7.1", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Poder Legislativo", "Assunto": "Estrutura", "Concluído": False},
    {"Código": "7.2", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Poder Legislativo", "Assunto": "Funcionamento e atribuições", "Concluído": False},
    {"Código": "7.3", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Processo legislativo", "Assunto": "-", "Concluído": False},
    {"Código": "7.3.1", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Processo legislativo", "Assunto": "Processo legislativo federal: conceito, espécies normativas, modalidades, fases", "Concluído": False},
    {"Código": "7.3.2", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Processo legislativo", "Assunto": "Processo legislativo estadual, distrital e municipal: normas constitucionais federais aplicáveis", "Concluído": False},
    {"Código": "7.4", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Fiscalização contábil", "Assunto": "Financeira e orçamentária", "Concluído": False},
    {"Código": "7.5", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Comissões parlamentares", "Assunto": "Comissões parlamentares de inquérito", "Concluído": False},
    {"Código": "8", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Poder Judiciário", "Assunto": "Disposições gerais", "Concluído": False},
    {"Código": "9", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Funções essenciais à justiça", "Assunto": "-", "Concluído": False},
    {"Código": "9.1", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Funções essenciais à justiça", "Assunto": "Ministério Público, advocacia pública", "Concluído": False},
    {"Código": "9.2", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Funções essenciais à justiça", "Assunto": "Advocacia privada e Defensoria Pública", "Concluído": False},
    {"Código": "10", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Controle de constitucionalidade", "Assunto": "-", "Concluído": False},
    {"Código": "10.1", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Controle de constitucionalidade", "Assunto": "Controle judicial de constitucionalidade: conceito, histórico, sistemas, pressupostos, modalidades, órgãos competentes, sujeitos legitimados, objetos de controle, tipos de inconstitucionalidade, parâmetros de controle, formalidades, procedimentos, julgamentos, decisões, efeitos das decisões, técnicas de decisão, segurança e estabilidade das decisões", "Concluído": False},
    {"Código": "10.2", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Controle de constitucionalidade", "Assunto": "Súmula vinculante", "Concluído": False},
    {"Código": "10.3", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Controle de constitucionalidade", "Assunto": "Reclamação constitucional", "Concluído": False},
    {"Código": "10.4", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Controle não judicial", "Assunto": "Órgãos, institutos e procedimentos", "Concluído": False},
    {"Código": "10.5", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Controle de constitucionalidade", "Assunto": "Nos estados e no Distrito Federal", "Concluído": False},
    {"Código": "11", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Ordem econômica e financeira", "Assunto": "-", "Concluído": False},
    {"Código": "12", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Finanças públicas", "Assunto": "-", "Concluído": False},
    {"Código": "13", "Grupo": "Geral Especifico", "Área": "DIREITO CONSTITUCIONAL", "Subárea": "Constituição do Estado de Sergipe", "Assunto": "-", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Fundamentos do direito empresarial", "Assunto": "-", "Concluído": False},
    {"Código": "1.1", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Fundamentos do direito empresarial", "Assunto": "Origem e evolução histórica, autonomia, fontes e características", "Concluído": False},
    {"Código": "1.2", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Fundamentos do direito empresarial", "Assunto": "Teoria da empresa", "Concluído": False},
    {"Código": "1.3", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Fundamentos do direito empresarial", "Assunto": "Empresário: conceito, caracterização, inscrição, capacidade; empresário individual; pequeno empresário", "Concluído": False},
    {"Código": "1.4", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Fundamentos do direito empresarial", "Assunto": "Lei Complementar nº 123/2006 e suas alterações (microempresa e empresa de pequeno porte)", "Concluído": False},
    {"Código": "1.5", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Fundamentos do direito empresarial", "Assunto": "Prepostos do empresário", "Concluído": False},
    {"Código": "1.6", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Fundamentos do direito empresarial", "Assunto": "Institutos complementares: nome empresarial, estabelecimento empresarial, escrituração", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Registro de empresa", "Assunto": "-", "Concluído": False},
    {"Código": "2.1", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Registro de empresa", "Assunto": "Órgãos de registro de empresa", "Concluído": False},
    {"Código": "2.2", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Registro de empresa", "Assunto": "Atos de registro de empresa", "Concluído": False},
    {"Código": "2.3", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Registro de empresa", "Assunto": "Processo decisório do registro de empresa", "Concluído": False},
    {"Código": "2.4", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Registro de empresa", "Assunto": "Inatividade da empresa", "Concluído": False},
    {"Código": "2.5", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Registro de empresa", "Assunto": "Empresário irregular", "Concluído": False},
    {"Código": "2.6", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Registro de empresa", "Assunto": "Lei nº 8.934/1994 e suas alterações", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "-", "Concluído": False},
    {"Código": "3.1", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Sociedade empresária: conceito, terminologia, ato constitutivo", "Concluído": False},
    {"Código": "3.2", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Sociedades simples e empresárias", "Concluído": False},
    {"Código": "3.3", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Personalização da sociedade empresária", "Concluído": False},
    {"Código": "3.4", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Classificação das sociedades empresárias", "Concluído": False},
    {"Código": "3.5", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Sociedade irregular", "Concluído": False},
    {"Código": "3.6", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Teoria da desconsideração da personalidade jurídica", "Concluído": False},
    {"Código": "3.7", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Desconsideração inversa", "Concluído": False},
    {"Código": "3.8", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Regime jurídico dos sócios", "Concluído": False},
    {"Código": "3.9", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Sociedade limitada", "Concluído": False},
    {"Código": "3.10", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Sociedade anônima", "Concluído": False},
    {"Código": "3.11", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Lei nº 6.404/1976 e suas alterações", "Concluído": False},
    {"Código": "3.12", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Sociedade em nome coletivo", "Concluído": False},
    {"Código": "3.13", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Sociedade em comandita simples", "Concluído": False},
    {"Código": "3.14", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Sociedade em comandita por ações", "Concluído": False},
    {"Código": "3.15", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Operações societárias: transformação, incorporação, fusão e cisão", "Concluído": False},
    {"Código": "3.16", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Relações entre sociedades: coligações de sociedades, grupos societários, consórcios, sociedade subsidiária integral, sociedade de propósito específico", "Concluído": False},
    {"Código": "3.17", "Grupo": "Geral Especifico", "Área": "DIREITO EMPRESARIAL", "Subárea": "Direito societário", "Assunto": "Dissolução, liquidação e extinção das sociedades", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Lei de Introdução às Normas do Direito Brasileiro", "Assunto": "-", "Concluído": False},
    {"Código": "1.1", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Lei de Introdução às Normas do Direito Brasileiro", "Assunto": "Vigência, aplicação, obrigatoriedade, interpretação e integração das leis", "Concluído": False},
    {"Código": "1.2", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Lei de Introdução às Normas do Direito Brasileiro", "Assunto": "Conflito das leis no tempo", "Concluído": False},
    {"Código": "1.3", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Lei de Introdução às Normas do Direito Brasileiro", "Assunto": "Eficácia das leis no espaço", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "-", "Concluído": False},
    {"Código": "2.1", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "Conceito", "Concluído": False},
    {"Código": "2.2", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "Existência da pessoa natural", "Concluído": False},
    {"Código": "2.3", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "Personalidade", "Concluído": False},
    {"Código": "2.4", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "Capacidade", "Concluído": False},
    {"Código": "2.5", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "Direitos da personalidade", "Concluído": False},
    {"Código": "2.6", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "Nome civil", "Concluído": False},
    {"Código": "2.7", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "Estado civil", "Concluído": False},
    {"Código": "2.8", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "Domicílio", "Concluído": False},
    {"Código": "2.9", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas naturais", "Assunto": "Ausência", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "-", "Concluído": False},
    {"Código": "3.1", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Disposições gerais", "Concluído": False},
    {"Código": "3.2", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Conceito e elementos caracterizadores", "Concluído": False},
    {"Código": "3.3", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Constituição", "Concluído": False},
    {"Código": "3.4", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Extinção", "Concluído": False},
    {"Código": "3.5", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Capacidade e direitos da personalidade", "Concluído": False},
    {"Código": "3.6", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Sociedades de fato", "Concluído": False},
    {"Código": "3.7", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Associações", "Concluído": False},
    {"Código": "3.8", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Sociedades", "Concluído": False},
    {"Código": "3.9", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Fundações", "Concluído": False},
    {"Código": "3.10", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Entes despersonalizados", "Concluído": False},
    {"Código": "3.11", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Desconsideração da personalidade jurídica", "Concluído": False},
    {"Código": "3.12", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Pessoas jurídicas", "Assunto": "Responsabilidade da pessoa jurídica e dos sócios", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Domicílio", "Assunto": "-", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Bens", "Assunto": "-", "Concluído": False},
    {"Código": "5.1", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Bens", "Assunto": "Diferentes classes", "Concluído": False},
    {"Código": "5.2", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Bens", "Assunto": "Bens corpóreos e incorpóreos", "Concluído": False},
    {"Código": "5.3", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Bens", "Assunto": "Bens no comércio e fora do comércio", "Concluído": False},
    {"Código": "5.4", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Bens", "Assunto": "Bens considerados em si mesmos", "Concluído": False},
    {"Código": "5.5", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Bens", "Assunto": "Bens reciprocamente considerados", "Concluído": False},
    {"Código": "5.6", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Bens", "Assunto": "Bens públicos", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Fato jurídico", "Assunto": "-", "Concluído": False},
    {"Código": "7", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "-", "Concluído": False},
    {"Código": "7.1", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "Disposições gerais", "Concluído": False},
    {"Código": "7.2", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "Classificação e interpretação", "Concluído": False},
    {"Código": "7.3", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "Elementos", "Concluído": False},
    {"Código": "7.4", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "Representação", "Concluído": False},
    {"Código": "7.5", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "Condição, termo e encargo", "Concluído": False},
    {"Código": "7.6", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "Defeitos do negócio jurídico", "Concluído": False},
    {"Código": "7.7", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "Existência, validade, eficácia", "Concluído": False},
    {"Código": "7.8", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "Invalidade do negócio jurídico", "Concluído": False},
    {"Código": "7.9", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Negócio jurídico", "Assunto": "Simulação", "Concluído": False},
    {"Código": "8", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Atos jurídicos", "Assunto": "Atos jurídicos lícitos e ilícitos", "Concluído": False},
    {"Código": "9", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Prescrição e decadência", "Assunto": "-", "Concluído": False},
    {"Código": "10", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Prova do fato jurídico", "Assunto": "-", "Concluído": False},
    {"Código": "11", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Direito de família", "Assunto": "-", "Concluído": False},
    {"Código": "11.1", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Direito de família", "Assunto": "Direito pessoal", "Concluído": False},
    {"Código": "11.2", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Direito de família", "Assunto": "Direito patrimonial", "Concluído": False},
    {"Código": "11.3", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Direito de família", "Assunto": "União estável", "Concluído": False},
    {"Código": "11.4", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Direito de família", "Assunto": "Tutela e curatela", "Concluído": False},
    {"Código": "12", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Direito das sucessões", "Assunto": "-", "Concluído": False},
    {"Código": "12.1", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Direito das sucessões", "Assunto": "Sucessão em geral", "Concluído": False},
    {"Código": "12.2", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Direito das sucessões", "Assunto": "Sucessão legítima", "Concluído": False},
    {"Código": "12.3", "Grupo": "Geral Especifico", "Área": "DIREITO CIVIL", "Subárea": "Direito das sucessões", "Assunto": "Sucessão testamentária", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Princípios do direito penal", "Assunto": "Princípios aplicáveis ao direito penal", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Aplicação da lei penal", "Assunto": "-", "Concluído": False},
    {"Código": "2.1", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Aplicação da lei penal", "Assunto": "A lei penal no tempo e no espaço", "Concluído": False},
    {"Código": "2.2", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Aplicação da lei penal", "Assunto": "Tempo e lugar do crime", "Concluído": False},
    {"Código": "2.3", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Aplicação da lei penal", "Assunto": "Interpretação da lei penal", "Concluído": False},
    {"Código": "2.4", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Aplicação da lei penal", "Assunto": "Analogia", "Concluído": False},
    {"Código": "2.5", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Aplicação da lei penal", "Assunto": "Irretroatividade da lei penal", "Concluído": False},
    {"Código": "2.6", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Aplicação da lei penal", "Assunto": "Conflito aparente de normas penais", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Ilicitude", "Assunto": "-", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Culpabilidade", "Assunto": "-", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Punibilidade", "Assunto": "Punibilidade e causas de extinção", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Crimes contra a administração pública", "Assunto": "-", "Concluído": False},
    {"Código": "7", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Abuso de autoridade", "Assunto": "Lei nº 13.869/2019", "Concluído": False},
    {"Código": "8", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Disposições constitucionais", "Assunto": "Disposições constitucionais aplicáveis ao direito penal", "Concluído": False},
    {"Código": "9", "Grupo": "Geral Especifico", "Área": "DIREITO PENAL", "Subárea": "Crimes contra a ordem tributária", "Assunto": "-", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "LEGISLAÇÃO TRIBUTÁRIA ESTADUAL", "Subárea": "-", "Assunto": "Lei Estadual nº 3.796/1996 e Decreto Estadual nº 21.400/2002 e anexos (Regulamento do ICMS)", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "LEGISLAÇÃO TRIBUTÁRIA ESTADUAL", "Subárea": "-", "Assunto": "Lei Estadual nº 7.651/2013 e Decreto Estadual nº 29.803/2014 (processo administrativo fiscal)", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "LEGISLAÇÃO TRIBUTÁRIA ESTADUAL", "Subárea": "-", "Assunto": "Programa Sergipano de Desenvolvimento Industrial – PSDI (Lei Estadual nº 3.140/1991 e alterações) e Decreto Estadual nº 29.935/2014", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "LEGISLAÇÃO TRIBUTÁRIA ESTADUAL", "Subárea": "-", "Assunto": "Fundo Estadual de Equilíbrio Fiscal (FEEF): Lei nº 8.180/2016 e Decreto nº 30.479/2017 (regulamento do FEEF)", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "LEGISLAÇÃO TRIBUTÁRIA ESTADUAL", "Subárea": "-", "Assunto": "Lei Estadual nº 7.655/2013 e Decreto Estadual nº 29.684/2014 (regulamento do IPVA)", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "LEGISLAÇÃO TRIBUTÁRIA ESTADUAL", "Subárea": "-", "Assunto": "Lei Estadual nº 7.724/2013 e Decreto Estadual nº 29.994/2015 (regulamento do ITCMD)", "Concluído": False},
    {"Código": "7", "Grupo": "Geral Especifico", "Área": "LEGISLAÇÃO TRIBUTÁRIA ESTADUAL", "Subárea": "-", "Assunto": "Lei Estadual nº 8.638/2019 (Taxa Estadual de Fiscalização e Serviços Diversos - TFSD)", "Concluído": False},
    {"Código": "8", "Grupo": "Geral Especifico", "Área": "LEGISLAÇÃO TRIBUTÁRIA ESTADUAL", "Subárea": "-", "Assunto": "Lei nº 4.731/2002 (Fundo Estadual de Combate e Erradicação da Pobreza e ICMS)", "Concluído": False},
    {"Código": "1", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "-", "Assunto": "Normas Brasileiras de Contabilidade de Auditoria – NBC TA e NBC PA", "Concluído": False},
    {"Código": "2", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "-", "Assunto": "Amostragem em Auditoria. NBC TA 530, aprovada pela Resolução CFC nº 1.222/2009", "Concluído": False},
    {"Código": "3", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "-", "Assunto": "Testes de observância", "Concluído": False},
    {"Código": "4", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "-", "Assunto": "Testes substantivos", "Concluído": False},
    {"Código": "5", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "-", "Assunto": "Testes para subavaliação e testes para superavaliação", "Concluído": False},
    {"Código": "6", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "-", "Assunto": "Evidências de auditoria", "Concluído": False},
    {"Código": "7", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "-", "Assunto": "Procedimentos de auditoria", "Concluído": False},
    {"Código": "8", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "-", "Assunto": "Identificação de fraudes na escrita contábil", "Concluído": False},
    {"Código": "9", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "-", "Assunto": "Demonstrações contábeis sujeitas a auditoria", "Concluído": False},
    {"Código": "10", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo circulante", "Assunto": "Auditoria no ativo circulante", "Concluído": False},
    {"Código": "10.1", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo circulante", "Assunto": "Recomposição contábil do fluxo de caixa da empresa", "Concluído": False},
    {"Código": "11", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo circulante", "Assunto": "Identificação de saldo credor na conta caixa por falta de emissão de documentos fiscais", "Concluído": False},
    {"Código": "12", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo circulante", "Assunto": "Suprimento das disponibilidades sem comprovação quanto à efetiva entrega dos recursos financeiros", "Concluído": False},
    {"Código": "13", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo circulante", "Assunto": "Aquisições de mercadorias, bens, serviços e outros ativos não contabilizados e sem comprovação da origem", "Concluído": False},
    {"Código": "14", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo circulante", "Assunto": "Baixa fictícia de títulos não recebidos", "Concluído": False},
    {"Código": "15", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo circulante", "Assunto": "Cotejamento de recebíveis com registros contábeis de receitas", "Concluído": False},
    {"Código": "16", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo não circulante", "Assunto": "Auditoria no ativo não circulante", "Concluído": False},
    {"Código": "16.1", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo não circulante", "Assunto": "Superavaliação na formação dos custos de estoque", "Concluído": False},
    {"Código": "17", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo realizável a longo prazo", "Assunto": "Auditoria no ativo realizável a longo prazo", "Concluído": False},
    {"Código": "17.1", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo realizável a longo prazo", "Assunto": "Identificação de origens de recursos fictícias", "Concluído": False},
    {"Código": "18", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Investimentos", "Assunto": "Auditoria em investimentos", "Concluído": False},
    {"Código": "19", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo imobilizado", "Assunto": "Auditoria no ativo imobilizado", "Concluído": False},
    {"Código": "19.1", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo imobilizado", "Assunto": "Ativos ocultos", "Concluído": False},
    {"Código": "20", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo imobilizado", "Assunto": "Alienação fictícia de bens", "Concluído": False},
    {"Código": "21", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Ativo intangível", "Assunto": "Auditoria no ativo intangível", "Concluído": False},
    {"Código": "22", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Passivo circulante", "Assunto": "Auditoria no passivo circulante", "Concluído": False},
    {"Código": "22.1", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Passivo circulante", "Assunto": "Falta de registro contábil dos passivos de curto prazo", "Concluído": False},
    {"Código": "23", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Passivo circulante", "Assunto": "Passivos fictícios", "Concluído": False},
    {"Código": "24", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Passivo circulante", "Assunto": "Identificação de passivos já pagos e não baixados", "Concluído": False},
    {"Código": "25", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Passivo não circulante", "Assunto": "Auditoria no passivo não circulante", "Concluído": False},
    {"Código": "26", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Patrimônio líquido", "Assunto": "Auditoria no patrimônio líquido", "Concluído": False},
    {"Código": "27", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Patrimônio líquido", "Assunto": "Aumento do capital social sem comprovação quanto à entrega dos recursos", "Concluído": False},
    {"Código": "28", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Patrimônio líquido", "Assunto": "Contabilização de reservas", "Concluído": False},
    {"Código": "29", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Patrimônio líquido", "Assunto": "Subvenções", "Concluído": False},
    {"Código": "30", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Contas de resultado", "Assunto": "Auditoria em contas de resultado", "Concluído": False},
    {"Código": "31", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Contas de resultado", "Assunto": "Registro de receitas e despesas", "Concluído": False},
    {"Código": "32", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Contas de resultado", "Assunto": "Ocultação de receitas", "Concluído": False},
    {"Código": "33", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Contas de resultado", "Assunto": "Superavaliação de custos e despesas", "Concluído": False},
    {"Código": "34", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Escrita fiscal", "Assunto": "Identificação de fraudes e erros na escrita fiscal", "Concluído": False},
    {"Código": "35", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Escrita fiscal", "Assunto": "Auditoria na escrita fiscal digital (EFD) e na NFe", "Concluído": False},
    {"Código": "36", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Escrita fiscal", "Assunto": "Testes de auditoria nos registros da NFe e demais controles ICMS", "Concluído": False},
    {"Código": "37", "Grupo": "Geral Especifico", "Área": "AUDITORIA FISCAL", "Subárea": "Sigilo bancário", "Assunto": "Lei Complementar nº 105/2001", "Concluído": False},
    {"Código": "1", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Gestão de TI", "Assunto": "Ciclo PDCA", "Concluído": False},
    {"Código": "2", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Gestão de TI", "Assunto": "Gerência de projetos: conceitos básicos", "Concluído": False},
    {"Código": "3", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Gestão de TI", "Assunto": "PMBOK 7ª edição", "Concluído": False},
    {"Código": "4", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Gestão de TI", "Assunto": "COBIT 2019", "Concluído": False},
    {"Código": "5", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Gestão de TI", "Assunto": "ITIL v4", "Concluído": False},
    {"Código": "6", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Gestão de TI", "Assunto": "Gerenciamento de processos de negócio: técnicas de mapeamento, modelos AS-IS, TO-BE e TO-RUN, análise e simulação de processos, construção e mensuração de indicadores", "Concluído": False},
    {"Código": "7", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Gestão de TI", "Assunto": "Modelagem de processos em BPMN: notação, artefatos e atividades, workflow, BPMS", "Concluído": False},
    {"Código": "8", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Gestão de TI", "Assunto": "Decision model and notation (DMN)", "Concluído": False},
    {"Código": "9", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Gestão de TI", "Assunto": "Noções de planejamento estratégico e tático de TIC", "Concluído": False},
    {"Código": "10", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Engenharia de software", "Concluído": False},
    {"Código": "11", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Ciclo de vida do software", "Concluído": False},
    {"Código": "12", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Análise e projeto de sistemas: padrões, práticas e princípios de orientação a objetos", "Concluído": False},
    {"Código": "12.1", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Design patterns", "Concluído": False},
    {"Código": "12.2", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Princípios SOLID", "Concluído": False},
    {"Código": "12.3", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Princípios GRASP", "Concluído": False},
    {"Código": "12.4", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Unified process", "Concluído": False},
    {"Código": "12.5", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "UML 2", "Concluído": False},
    {"Código": "12.6", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Domain Driven Design", "Concluído": False},
    {"Código": "12.7", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Arquitetura hexagonal (portas e adaptadores)", "Concluído": False},
    {"Código": "13", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Metodologias de desenvolvimento de software", "Concluído": False},
    {"Código": "14", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Métricas e estimativas de software", "Concluído": False},
    {"Código": "15", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Qualidade de software", "Concluído": False},
    {"Código": "16", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "CMMI-DEV v2.0, MR-MPS-SW, Guia Geral MPS de Software (2021)", "Concluído": False},
    {"Código": "17", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Engenharia de requisitos: conceitos básicos, técnicas de elicitação e especificação", "Concluído": False},
    {"Código": "18", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Metodologias e práticas ágeis", "Concluído": False},
    {"Código": "18.1", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Scrum", "Concluído": False},
    {"Código": "18.2", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "XP", "Concluído": False},
    {"Código": "18.3", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Kanban", "Concluído": False},
    {"Código": "18.4", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Especificação por exemplo", "Concluído": False},
    {"Código": "18.5", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Domain-driven design (DDD)", "Concluído": False},
    {"Código": "19", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Testes de software (unidade, integração, sistema, aceitação, regressão, desempenho, vulnerabilidade, usabilidade e carga)", "Concluído": False},
    {"Código": "20", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Criptografia: conceitos básicos e aplicações", "Concluído": False},
    {"Código": "20.1", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Protocolos criptográficos", "Concluído": False},
    {"Código": "20.2", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Criptografia simétrica e assimétrica", "Concluído": False},
    {"Código": "20.3", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Principais algoritmos", "Concluído": False},
    {"Código": "21", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Assinatura digital", "Concluído": False},
    {"Código": "22", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Certificado digital", "Concluído": False},
    {"Código": "23", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Sistemas de Informação", "Assunto": "Desenvolvimento seguro de software: OWASP", "Concluído": False},
    {"Código": "24", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Linguagens de definição e manipulação de dados em SGBDs relacionais", "Concluído": False},
    {"Código": "25", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Modelagem de dados: modelos relacional e multidimensional", "Concluído": False},
    {"Código": "26", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Administração de banco de dados relacionais", "Concluído": False},
    {"Código": "26.1", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Projeto e implantação de SGBDs relacionais (SQL Server, Oracle, MySQL, PostgreSQL)", "Concluído": False},
    {"Código": "26.2", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Administração de usuários e perfis de acesso", "Concluído": False},
    {"Código": "26.3", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Controle de proteção, integridade e concorrência", "Concluído": False},
    {"Código": "26.4", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Backup e restauração de dados", "Concluído": False},
    {"Código": "26.5", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Tolerância a falhas e continuidade de operação", "Concluído": False},
    {"Código": "26.6", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Monitoramento e otimização de desempenho, cluster de banco de dados", "Concluído": False},
    {"Código": "27", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Pipeline de dados: fundamentos, orquestração, integração, ETL, ELT e ferramentas", "Concluído": False},
    {"Código": "28", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "OLAP", "Concluído": False},
    {"Código": "29", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Técnicas de modelagem e otimização de bases de dados multidimensionais", "Concluído": False},
    {"Código": "30", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Técnicas para pré-processamento de dados", "Concluído": False},
    {"Código": "31", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Processamento distribuído", "Concluído": False},
    {"Código": "32", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Data lake", "Concluído": False},
    {"Código": "33", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Conceitos, arquiteturas, técnicas e tarefas de data mining e data warehouse", "Concluído": False},
    {"Código": "34", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Big data: conceito, premissas, análise de dados e aplicações", "Concluído": False},
    {"Código": "35", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Ecossistema Hadoop: conceitos, arquitetura, componentes e implantação", "Concluído": False},
    {"Código": "36", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Spark: conceitos, arquitetura e aplicações", "Concluído": False},
    {"Código": "37", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Bancos de dados não relacionais: fundamentos, administração, desempenho e configuração", "Concluído": False},
    {"Código": "38", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Banco de Dados", "Assunto": "Massive Parallel Processing (MPP)", "Concluído": False},
    {"Código": "39", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Fundamentos de ciência de dados", "Concluído": False},
    {"Código": "40", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Classificação", "Concluído": False},
    {"Código": "41", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Coleta, tratamento, armazenamento, integração e recuperação de dados", "Concluído": False},
    {"Código": "42", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Regras de associação", "Concluído": False},
    {"Código": "43", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Modelagem relacional e multidimensional", "Concluído": False},
    {"Código": "44", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Aprendizagem de máquina: fundamentos, principais algoritmos e métricas de desempenho", "Concluído": False},
    {"Código": "45", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Regressão linear", "Concluído": False},
    {"Código": "46", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Regressão logística", "Concluído": False},
    {"Código": "47", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Análise de agrupamentos (clusterização)", "Concluído": False},
    {"Código": "48", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Classificação", "Concluído": False},
    {"Código": "49", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Detecção de anomalias", "Concluído": False},
    {"Código": "50", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Modelagem preditiva", "Concluído": False},
    {"Código": "51", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Visão computacional", "Concluído": False},
    {"Código": "52", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Mineração de texto", "Concluído": False},
    {"Código": "53", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Redes neurais artificiais", "Concluído": False},
    {"Código": "54", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Deep learning", "Concluído": False},
    {"Código": "55", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Visualização e análise exploratória de dados", "Concluído": False},
    {"Código": "56", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Business Intelligence", "Concluído": False},
    {"Código": "57", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Ciência de Dados", "Assunto": "Inteligência Artificial (RAG e LLM)", "Concluído": False},
    {"Código": "58", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Fundamentos", "Concluído": False},
    {"Código": "59", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Confidencialidade, integridade, disponibilidade, autenticidade e não repúdio", "Concluído": False},
    {"Código": "60", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Classificação e controle dos ativos de informação", "Concluído": False},
    {"Código": "61", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Políticas de segurança", "Concluído": False},
    {"Código": "62", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Políticas de classificação da informação", "Concluído": False},
    {"Código": "63", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Normas ABNT NBR ISO/IEC 27001, 27002, 27005, 22301", "Concluído": False},
    {"Código": "64", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Lei nº 13.709/2018 (LGPD)", "Concluído": False},
    {"Código": "65", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Gerenciamento de acesso e identidade: IAM, RBAC", "Concluído": False},
    {"Código": "66", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Segurança de redes de computadores: firewall, IDS, antivírus, NAT, VPN", "Concluído": False},
    {"Código": "67", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Prevenção e tratamento de incidentes", "Concluído": False},
    {"Código": "68", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Gestão de riscos: ameaça, vulnerabilidade, impacto e formas de tratamento de riscos", "Concluído": False},
    {"Código": "69", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Gestão de continuidade de negócio", "Concluído": False},
    {"Código": "70", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Conceitos e tipos de ataques cibernéticos", "Concluído": False},
    {"Código": "71", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Conceitos e tipos de malwares", "Concluído": False},
    {"Código": "72", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Conceitos de monitoramento e análise de tráfego", "Concluído": False},
    {"Código": "73", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Criptografia: conceitos básicos, protocolos, simétrica/assimétrica, principais algoritmos", "Concluído": False},
    {"Código": "74", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "HTTPS/SSL", "Concluído": False},
    {"Código": "75", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "Certificado digital: tipos, padrões X.509 e ICP-Brasil", "Concluído": False},
    {"Código": "76", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Segurança da Informação", "Assunto": "DevSecOps: conceitos", "Concluído": False},
    {"Código": "77", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Fiscalização de Contratos de TI", "Assunto": "Gestão de contratação de soluções de TI", "Concluído": False},
    {"Código": "78", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Fiscalização de Contratos de TI", "Assunto": "Legislação aplicável à contratação de bens e serviços de TI", "Concluído": False},
    {"Código": "78.1", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Fiscalização de Contratos de TI", "Assunto": "Lei nº 14.133/2021 (Nova Lei de Licitações e Contratos)", "Concluído": False},
    {"Código": "78.2", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Fiscalização de Contratos de TI", "Assunto": "Instrução Normativa SGD/SEDGG/ME nº 94/2022", "Concluído": False},
    {"Código": "78.3", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Fiscalização de Contratos de TI", "Assunto": "Instrução Normativa SEGES/ME 65/2021", "Concluído": False},
    {"Código": "79", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Fiscalização de Contratos de TI", "Assunto": "Elaboração e fiscalização de contratos de TI: critérios, cláusulas, indicadores, papel do fiscalizador, acompanhamento e penalidades", "Concluído": False},
    {"Código": "80.1", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Serviços de Computação em Nuvem", "Assunto": "Conceitos de Computação em Nuvem: Elasticidade, Autoatendimento, pay-per-use", "Concluído": False},
    {"Código": "80.2", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Serviços de Computação em Nuvem", "Assunto": "Tipos de nuvem: Nuvem privada, híbrida e pública (AWS, Azure)", "Concluído": False},
    {"Código": "80.3", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Serviços de Computação em Nuvem", "Assunto": "Modelos de serviço: IaaS, PaaS e SaaS", "Concluído": False},
    {"Código": "80.4", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Serviços de Computação em Nuvem", "Assunto": "Infraestrutura como código (ex.: Ansible)", "Concluído": False},
    {"Código": "80.5", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Serviços de Computação em Nuvem", "Assunto": "Arquitetura Serverless", "Concluído": False},
    {"Código": "80.6", "Grupo": "Especifico", "Área": "TECNOLOGIA DA INFORMAÇÃO", "Subárea": "Serviços de Computação em Nuvem", "Assunto": "Vantagens e desvantagens de cada tipo de nuvem", "Concluído": False},


        
    ])


edited_df = st.data_editor(st.session_state.syllabus, num_rows="dynamic", use_container_width=True)
st.session_state.syllabus = edited_df

# Resumo
concluidos = edited_df["Concluído"].sum()
total = len(edited_df)
st.success(f"📌 Você concluiu {concluidos}/{total} tópicos do edital!")
